name: Node
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node 12
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
        id: node

      - name: Check out code
        uses: actions/checkout@v1

      - run: yarn install

      - name: Run tests
        run: yarn test

      - name: Lint
        run: yarn run lint

      - name: Build
        run: yarn run build

      - name: Test pack
        if: github.ref != 'refs/heads/master'
        run: yarn pack

      - name: Download releaser
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          wget https://github.com/Nightapes/go-semantic-release/releases/download/1.1.1/go-semantic-release 
          chmod +x ./go-semantic-release
          yarn version --new-version $(./go-semantic-release next)

      - name: Release npm
        if: github.ref == 'refs/heads/master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          ./go-semantic-release release
          echo "//registry.npmjs.com/:_authToken=$GITHUB_PAT" >>~/.npmrc
          yarn publish
          yarn config set registry https://npm.pkg.github.com/
          # rm ~/.npmrc
          # echo "//npm.pkg.github.com/:_authToken=$GITHUB_TOKEN" >>~/.npmrc
          # yarn publish
